name: Build Repo Listing

on: 
  workflow_dispatch:
  push:
    branches: main
    paths: source.json

# GITHUB_TOKENの権限を設定してGitHub Pagesへのデプロイを許可
permissions:
  contents: read
  pages: write
  id-token: write
  
# 1つの同時デプロイを許可
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:
  
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3 # このリポジトリをチェックアウト
      - uses: actions/checkout@v3 # 自動化リポジトリをチェックアウト
        with:
          repository: vrchat-community/package-list-action
          path: ${{env.pathToCi}}
          clean: false # そうしないとローカルリポジトリがチェックアウトされなくなる
          
      - name: キャッシュの復元
        uses: actions/cache@v3
        with:
          path: |
            ${{env.pathToCi}}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: パッケージバージョンリストのビルド
        run: ${{env.pathToCi}}/build.cmd BuildMultiPackageListing --root ${{env.pathToCi}} --list-publish-directory $GITHUB_WORKSPACE/${{env.listPublishDirectory}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Pagesのセットアップ
        uses: actions/configure-pages@v3
        
      - name: アーティファクトのアップロード
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{env.listPublishDirectory}}
          
      - name: GitHub Pagesへのデプロイ
        id: deployment
        uses: actions/deploy-pages@v2
